required_environment_variables = [
  'MONGODB_URI',
  'CLERK_SECRET_KEY',
  'CLERK_PUBLISHABLE_KEY'
]

base_guild_id = '1253092552404631582'
frontend_url = 'https://dscforum.com'

[server]
port = 3004

[client]
port = 3000

[logger.levels]
error = 'red'
warn = 'yellow'
info = 'blue'
debug = 'grey'
database = 'magenta'
http = 'yellow'